### ISSUE TITLE
Use FS in Vue component

### ISSUE THREAD

**Issue by Bholtland** [shellyln/vue-electron-typescript-quickstart#12]
Hi, sorry to post this as an issue, but I'm trying to expose 'fs' module to Vue components, but I can't figure it out. Do you have an idea how to do this with this boilerplate? Thanks for setting it up by the way!

**Comment by shellyln** [comment]
You can expose Node.js `fs` module by using "node integration".
However, this is **too dangerous and not recommended**.
https://stackoverflow.com/questions/44391448/electron-require-is-not-defined.

You **SHOULD** use the IPC feature.
https://www.electronjs.org/docs/api/context-bridge

**Comment by Bholtland** [comment]
Thanks, I will look into that!
