### ISSUE TITLE
Permission denied NotAllowedError when navigator.MediaDevices.getUserMedia()

### ISSUE THREAD

**Issue by aoslee** [shellyln/vue-electron-typescript-quickstart#13]
hi:
  As is  the title. The media has granted on the windows 10. Did I need changing anything?
   OS: Windows 10
   electron: 11.1.1

Best regards

**Comment by shellyln** [comment]
Hi, @aoslee !
Please check your `webContents.session.setPermissionRequestHandler`.

https://github.com/shellyln/vue-electron-typescript-quickstart/blob/523b911fb9a40825b13e27590ddd6aec771c2204/src.mainproc/windows/MainWindow.ts#L74-L86

https://www.electronjs.org/docs/tutorial/security#4-handle-session-permission-requests-from-remote-content

**Comment by aoslee** [comment]
Hi @shellyln : 
   Thanks for replying.
    I annotated   mainWindow.webContents.session.setPermissionRequestHandler and  set contextIsolation to false ,navigator.MediaDevices.getUserMedia() is ok .  But I don't understand why. 
    Best regards
