### ISSUE TITLE
Not allowed to load a resource

### ISSUE THREAD

**Issue by Lothindir** [shellyln/vue-electron-typescript-quickstart#2]
Hello, I have a problem with the output of the build on Windows. While in a dev environment everything works fine. But when I build the exe files nothing appears in the window and the following message is written in the dev console :

```Not allowed to load local resource: file:///C:/Users/**/AppData/Local/Temp/1ZXB9Ph3Iq8saGYCyroEB2so16C/resources/app.asar/dist/main-window.html```

I tried building your template without changing anything and it's the same.

Electron-builder log :

```
• electron-builder  version=22.4.1 os=10.0.18363
• packaging       platform=win32 arch=x64 electron=8.0.1 appOutDir=dist\win-unpacked
```

**Comment by shellyln** [comment]
Hi, @Lothindir !
Thank you for reporting the issue.
I can't reproduce your error. Contents are loaded in exe.
(from `win-unpacked` and installed)
Is this just after clone?

```
  • electron-builder  version=22.3.2 os=10.0.18363
  • loaded configuration  file=D:\src\vue-electron-typescript-quickstart\electron-builder.yml
  • author is missed in the package.json  appPackageFile=D:\src\vue-electron-typescript-quickstart\package.json
  • writing effective config  file=dist.electron\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=8.0.1 appOutDir=dist.electron\win-unpacked
  • default Electron icon is used  reason=application icon is not set
  • building        target=nsis file=dist.electron\vue-electron-typescript-quickstart Setup 0.1.4.exe archs=x64 oneClick=true perMachine=false
  • do not use "your.id" as appId, "com.electron.vue-electron-typescript-quickstart" will be used instead
  • do not use "your.id" as appId, "com.electron.vue-electron-typescript-quickstart" will be used instead
  • building block map  blockMapFile=dist.electron\vue-electron-typescript-quickstart Setup 0.1.4.exe.blockmap
```

**Comment by Lothindir** [comment]
Hello, thank for your quick response !
I dug around a bit and I realized that I forgot to build the template before packaging it. So no problem with that. Sry 😅 

After a bit of tweaking the `electron-builder.yml` config file I found a solution. I had deleted those two lines in my project :
```yaml
directories:
  output: dist.electron
```

Apparently if you build the app in the `dist` folder and the you try to package the app in the same folder breaks everything. Changing the output directory for electron-builder resolved the issue.
I then tried to change the directory to anything else apart from `dist` and it still works.

**Solution** : Set the output directory of electron-builder to anything else than `dist`

**Comment by shellyln** [comment]
Hi, thanks for trying.

The output directoies are originally set as follows:
* electron renderer process: `dist/`
* electron main process: `bin/`
* electron packaging: `dist.electron/`

You need to build with the following steps:
1. `npm run build`
1. `npm run build:mainproc`
1. `npm run dist`
