### ISSUE TITLE
Confused about directory structure.

### ISSUE THREAD

**Issue by SmashingQuasar** [shellyln/vue-electron-typescript-quickstart#8]
Hey!

First of all, you are a lifesaver. I was pulling my hair trying to make this combo work until I found your boilerplate. Thanks a lot!

Now I am confused about three directories.
I don't understand what are `src.mainproc` and `src.preload`. It looks like `src.mainproc` is the Electron code and `src` is Vue.

Could you clarify the difference between `src.mainproc`, `src.preload` and `src`, please? Are they separated for compilation purposes? If so, how can I use Vue components in Electron code? This is mostly when communicating through ipcRenderer.

Thanks!

**Comment by shellyln** [comment]
Hi, @SmashingQuasar !

* `src.mainproc`: This is for Electron main process.
    (In other words, it is a script on the `Node.js` side.)
* `src`: This is for Electron renderer process. This will be run by BrowserWindow.
   (In other words, it is a script on the `Browser` side.)
* `src.preload`: This is Electron renderer process `preload` script.
    Exposed `Node.js/Electron` objects by this script can be used in the renderer process even if `nodeIntegration` is false.

Please see documents ([1](https://www.electronjs.org/docs/tutorial/application-architecture)) ([2](https://www.electronjs.org/docs/tutorial/context-isolation)) ([3](https://www.electronjs.org/docs/api/browser-window)).

**Comment by shellyln** [comment]
You can use Vue only in `Electron renderer process` (`src/`) codes.

**Comment by SmashingQuasar** [comment]
Thanks a lot that clarifies things!

Just one last question, what's the use for the `bin` directory?

Thanks!

**Comment by shellyln** [comment]
`bin/` is output directory for building `src.mainproc`,
Please see `webpack.mainproc.config.js`.
